module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.descriptions = [
    "Un refuge en pleine nature, entouré de montagnes majestueuses.",
    "Découvrez la magie de la forêt dans notre camp caché.",
    "Vivez une expérience unique au cœur de la vallée verdoyante.",
    "Des aventures palpitantes vous attendent dans notre camp d'aventure.",
    "Plongez dans la tranquillité d'un camp au bord d'un lac cristallin.",
    "Un coin de paradis pour les amoureux de la nature et de la randonnée.",
    "Profitez de nuits étoilées et de feux de camp chaleureux.",
    "Détendez-vous sur les rives d'une rivière paisible et claire.",
    "L'endroit idéal pour une retraite de camping paisible et relaxante.",
    "Explorez la faune et la flore riches de notre camp préservé.",
    "Loin de l'agitation de la ville, trouvez la paix dans notre camp isolé.",
    "Un sanctuaire pour les amateurs de plein air et les passionnés de camping.",
    "L'atmosphère magique d'une forêt enchantée vous accueille ici.",
    "Vivez l'expérience ultime de camping dans les montagnes enneigées.",
    "Des vues à couper le souffle vous attendent à chaque tournant.",
    "Plongez dans une aventure de camping le long des sentiers sauvages.",
    "Un coin tranquille pour se ressourcer et se reconnecter avec la nature.",
    "L'endroit parfait pour observer les étoiles et la voie lactée.",
    "Explorez les gorges profondes et les cascades spectaculaires de la région.",
    "Une oasis de paix nichée au cœur de la forêt ancienne.",
    "Reconnectez-vous avec la nature dans notre camp éco-responsable.",
    "Vivez des moments magiques au bord d'un lac miroir cristallin.",
    "Le camp idéal pour les amateurs de pêche et de canoë-kayak.",
    "Une expérience immersive au sein de la faune et de la flore locales.",
    "L'endroit rêvé pour les amateurs de photographie de paysages.",
    "Un refuge confortable pour les aventuriers en quête d'authenticité.",
    "Des soirées autour du feu sous un ciel étoilé inoubliable.",
    "Découvrez les mystères de la forêt lors de vos randonnées matinales.",
    "Un camp pour les âmes en quête de sérénité et de méditation.",
    "L'endroit parfait pour un séjour en famille rempli d'aventures.",
    "Des nuits paisibles bercées par le chant des oiseaux et du ruisseau.",
    "Laissez-vous envoûter par les légendes et les contes de la région.",
    "Un refuge rustique pour les amateurs de camping authentique.",
    "Profitez de l'air pur et des vues panoramiques depuis notre camp.",
    "L'endroit idéal pour s'éloigner de tout et se recentrer sur l'essentiel.",
    "Des couchers de soleil spectaculaires surplombant les montagnes lointaines.",
    "Découvrez les sentiers de randonnée secrets de la région.",
    "Un camp pour les aventuriers en quête de défis et de découvertes.",
    "Soyez témoin de la magie de la nature dans toute sa splendeur.",
    "Des soirées éclairées par la lueur des étoiles et des lucioles.",
    "Vivez l'expérience d'un camp authentique au cœur de la nature.",
    "Des moments de paix et de réflexion au bord d'un lac tranquille.",
    "Un refuge pour les amateurs d'ornithologie et de faune sauvage.",
    "Découvrez les merveilles cachées des forêts anciennes.",
    "L'endroit parfait pour les passionnés d'observation des étoiles.",
    "Plongez dans l'histoire et la culture locales lors de vos excursions.",
    "Un camp pour les esprits aventureux en quête de nouvelles expériences.",
    "Des matins emplis de chants d'oiseaux et de brises fraîches.",
    "Sentez la connexion profonde avec la terre dans notre camp rustique.",
    "Laissez-vous envoûter par la beauté sauvage de la nature qui vous entoure."
];


module.exports.price = ["0", "10", "15", "20",
    "25", "30", "35", "40",
    "45", "50", "60", "70",
    "80", "90", "100", "110",
    "120", "130", "140", "150"]
